### ISSUE TITLE
Internal globals based implementation makes it harder to use than it should be

### ISSUE THREAD

**Issue by autarch** [celogeek/perl-memory-stats#1]
I like this module but the fact that it's based on globals internally needlessly limits its use cases. I want to be able to measure overall memory use for a chunk of code at the same time as I measure subsections of that chunk.

I don't think there's any reason that this has to be done with globals. We have an object, so why not use it to hold state?

**Comment by celogeek** [comment]
You are right. I will apply the change. 
May be also doing something more obvious and simple to use.

**Comment by celogeek** [comment]
fixed v0.02

I will add more features now
